### ISSUE TITLE
dnsfilexfer is empty

### ISSUE THREAD

**Issue by g33xter** [danielmiessler/egression#1]
dnsfilexfer directory is empty so it's spitting this error.

![screen shot 2017-07-26 at 23 16 38](https://user-images.githubusercontent.com/8503135/28656760-9968ae78-7258-11e7-993a-0bd2e0b2ec26.png)

**Comment by danielmiessler** [comment]
Yes, I'm looking to fix that. Check the installer notes and it'll have a separate git clone for that package. I'm going to try to fix it in an update soon.

**Comment by danielmiessler** [comment]
Ok, this should be fixed now.

Just update the repo and it should fix.

You no longer have to download the dnsfilexfer piece separately. It's all included in the first clone now.

**Comment by g33xter** [comment]
Thank you so much.
